name: Hello Actions
on: push
jobs:
  build:
    name: Build and Deploy to Stage Server
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello World"
      - run: node --version
      - run: npm --version
      - run: yarn --version
      - run: yarn install
      - run: yarn test --watchAll=false
      - run: yarn build
      - run: rsync -avz -e 'ssh' build/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: build
