name: Hello Actions
on: push
jobs:
  build:
    name: Hello world action
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: echo "Hello World"
      - run: node --version
      - run: npm --version
      - run: yarn --version
